version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
  web_server:
    build:
      context: .
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672
    command: ["python3", "celery_example.py"]
    volumes:
      - .:/app
    links:
      - worker
    ports:
      - "5000:5000"
  worker:
    build:
      context: .
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672
    command: ["celery", "-l", "info", "-A", "celery_example.celery", "worker"]
    volumes:
      - .:/app
    links:
      - rabbitmq